### ISSUE TITLE
Nothing happens on 9.00

### ISSUE THREAD

**Issue by eros-fabbri** [Nazky/PS4Linux-Payloads#1]
i loaded the bin with netcat and payload guest but nothing is happening..

**Comment by mangowxlf** [comment]
did you send miraloader first?
you have to send miraloader to port 9020 and then send the linux payload to port 9021 once miraloader is waiting for clients

**Comment by C0nvert** [comment]
miraloader is not ready for 9.00 am i right?

**Comment by eros-fabbri** [comment]
> did you send miraloader first?
> you have to send miraloader to port 9020 and then send the linux payload to port 9021 once miraloader is waiting for clients

Yes , turns out that i had the wrong version of mira and it wasn’t working as it should.
