### ISSUE TITLE
PS4 PRO 5.3.18 Kernel Beta no signal, but power LEDs glow purple/blue

### ISSUE THREAD

**Issue by atr4593** [Nazky/PS4Linux-Payloads#13]
**PS4 PRO Model** - CUH 7215B, usual Linux settings (1080p, no HDMI link, dhcp, RGB auto)
**Linux Distro** - Manjaro, already installed on hard drive
**HDD** - My Passport Ultra Titanium 1TB
**TV** - Amazon FireTV 4K
Normally, when a kernel doesn't work on my PS4, there is no signal, the power LED stays white and the system will shut off at the touch of a key. However, with the latest kernel beta you released (5.3.18 beta), I get the same no signal issue, but the light alternates between blue/purple as if its working normally. The HDD activity light doesn't blink either. Briefly unplugging HDMI on both ends doesn't solve the issue as it normally would on certain kernels. 4.14.93 starts up properly, but there's no network functions sadly and ip a only shows loopback.
I'm only interested in this kernel in hopes that it will be the one to help fix the no eth/wifi/BT issue that plagues my particular model.

**Comment by Nazky** [comment]
a new kernel is maybe going to come with some fixes

**Comment by atr4593** [comment]
Thanks for the response and your work, documentation on PS4 Linux is sadly sparse so folks like you help a ton :) have a nice day
