### ISSUE TITLE
Nouveau Linux

### ISSUE THREAD

**Issue by ericwot12** [Nazky/PS4Linux-Payloads#14]
Écoutez je vais être sincère avec vous si vous êtes un des meilleurs mais il y a un truc qui m'énerve c'est que vous donnez pas tous les liens vous mettez la moitié et vous expliquer pas comment installer rapidement Linux vous donner les liens et après se débrouiller vous je peux comprendre que vous êtes très sympa de votre part mais s'il vous plaît mettez les liens complet quand vous faites une description ou un Linux sur le nouveau Linux que vous avez fait tout à l'heure il y a pas tout qui en discription il y a que le Linux avec pour l'installer dans le disque dur et encore même là on sait même pas quoi faire

**Comment by Nazky** [comment]
cette page est un tuto pour installer linux, sur youtube y a des centaine de vidéos pour installer linux, hier modded warfare a sortie un vidéos pour installer linux, j'ai clairement dit sur twitter et sur cette page que pour installer linux sur le hdd il faut une ps4 compatible (donc en gros faut tester), bientôt modded warfare va sortir une vidéo pour installer linux sur le hdd aussi, j'ai mis les liens du kernel (bzimage) et du initramfs sur cette page, j'ai donner le lien du nouveau initramfs que j'ai compilé sur twitter, si après tous sa vous arrivé pas a installer linux je peut rien y faire désoler
