### ISSUE TITLE
Question About VRAM

### ISSUE THREAD

**Issue by gabriel-maxx** [Nazky/PS4Linux-Payloads#2]
hello I would like to know if it is possible to create payloads with 6gb or 7gb? even if it's dangerous it's just a curiosity, or is 5gb really the limit?

**Comment by Nazky** [comment]
you can but it's not really useful you need to change the max vram in the main and the default vram on the makefile

**Comment by gabriel-maxx** [comment]
> you can but it's not really useful you need to change the max vram in the main and the default vram on the makefile

so 5gb is useful, 6gb or 7gb would not be useful, could you explain better why?

**Comment by GrassHydra** [comment]
> > you can but it's not really useful you need to change the max vram in the main and the default vram on the makefile
> 
> so 5gb is useful, 6gb or 7gb would not be useful, could you explain better why?

You need to compile the files yourself, as Nazky said.
Just "change the max vram in the main and the default vram on the makefile" and you're good to go... provided you know how to compile source code...

**Comment by gabriel-maxx** [comment]
@GrassHydra I already know how to change vram, wondering why 6gb or 7gb is not as useful as 5gb like @nazky said...

**Comment by Nazky** [comment]
because you going to allocate to the vram and the os is going to be a little laggy for what i have test but you can try on you'r side just don't try to put 8gb vram just in case i have never try so i don't know what it's going to happen lol

**Comment by gabriel-maxx** [comment]
> because you going to allocate to the vram and the os is going to be a little laggy for what i have test but you can try on you'r side just don't try to put 8gb vram just in case i have never try so i don't know what it's going to happen lol

thanks
