### ISSUE TITLE
USB Hard Drive not supported?

### ISSUE THREAD

**Issue by VirusBurst** [Nazky/PS4Linux-Payloads#24]
I was wondering, if the payload doesn't support booting of a USB hard drive for... reasons... 

I tried with an USB 3.0 Adapter to a SATA 160GB HDD, MBR and formatted to FAT32 with all the files in...
But after loading the payload, nothing happens... just stays the way it is...

PS4 Slim with Belize Southbridge
GoldHEN 2.2.5b7 @ FW 9.00
Successfully booted with an 64GB USB Stick but not with an USB HDD
Oh and if needed, Kernel 5.4.210 by whitehax0r and Steam OS 3.0

**Comment by Nazky** [comment]
you should be able to put i have myself use a 2tb hdd to usb using a adapter and it work maybe try to put the file in the internal hdd to put to rescushell then check if the usb hdd is detect if yes then install normally if not maybe the hdd is not formated well

**Comment by VirusBurst** [comment]
Got it! Looks like that the LinuxLoader doesn't always work immediately but up to 95% it does :)

Now I have to figure out the perfect combo between Kernel and Linux so I don't face the black screen issue after rescueshell boot into Linux
