### ISSUE TITLE
Internal Drive loader

### ISSUE THREAD

**Issue by DoganM95** [Nazky/PS4Linux-Payloads#5]
Could you create another variant that loads up from the internal drive, [like it was possible on 5.05](https://www.psxhax.com/threads/installing-linux-on-internal-ps4-hard-drive-hdd-5-05-loader-payload.6800/) ?

I see a huge performance uplift possibility here, comparing an internal sata ssd to a usb drive as OS storage.

**Comment by Nazky** [comment]
you aleardy can install linux in you'r internal hdd with this payload i am going soon to make a tuto on this page to show the best way to do it

**Comment by DoganM95** [comment]
Perfect, thanks!
