### ISSUE TITLE
Internal HDD (Gentoo)

### ISSUE THREAD

**Issue by gabriel-maxx** [Nazky/PS4Linux-Payloads#7]
Hi, I would like to know about installing on internal HDD using gentoo, as far as I know the tutorials on how to install gentoo are different from arch linux, so I think instead of using those commands you said, I could just put the image "ps4gentoo01-2020.img in /system/home, bzimage, initramfs.cpio.gz in /user/system/boot, am I right?

**Comment by Nazky** [comment]
i never try to install or run gentoo so idk sorry :( you can try to put the img in system/home and rename it linux.img
