### ISSUE TITLE
PS4 Kernel 5XX Help

### ISSUE THREAD

**Issue by gabriel-maxx** [Nazky/PS4Linux-Payloads#8]
Hi, I have a PS4 slim CUH-2215B, I tested the kernel (belize) 4.19.93 on the main page and it worked perfectly, but when I try 5.3.18 (BETA) I get several things and then "run /init as init process" for about 5 seconds and black screen, could you recommend a 5xx kernel compatible with my model please?

**Comment by Nazky** [comment]
the black screen is a problem of this beta kernel you have to resfresh the screen if you don't how do it the simple thing to do is just wait until the os go to rest mod (wait until you get no signal) then move the mouse or press a keyb in the keyboard the hdmi is going to refresh and you going to see the os again

**Comment by gabriel-maxx** [comment]
> the black screen is a problem of this beta kernel you have to resfresh the screen if you don't how do it the simple thing to do is just wait until the os go to rest mod (wait until you get no signal) then move the mouse or press a keyb in the keyboard the hdmi is going to refresh and you going to see the os again

thanks I did what you said and it works but you said this is a bug so it means it can be fixed, do you know how to do this? I wanted this kernel to boot like 4.19.93, no black screen...

**Comment by Nazky** [comment]
someone work on a more recent kernel and i also try thing on my side so yeah maybe this can be fixed soon

**Comment by gabriel-maxx** [comment]
> someone work on a more recent kernel and i also try thing on my side so yeah maybe this can be fixed soon

thanks
